# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rock Paper Scissor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Starscream', '~> 3.0.2'

  # Pods for Rock Paper Scissor

  target 'Rock Paper ScissorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rock Paper ScissorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
