# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bluetooth_Arduino_Sensing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bluetooth_Arduino_Sensing
  pod 'Charts'

  target 'Bluetooth_Arduino_SensingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bluetooth_Arduino_SensingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
